version: '3.8'

networks:
  web-net-50:
    name: 'web-net-50'
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.0.0/16
          gateway: 172.50.0.1

services:
  flask-app:
    container_name: 'flask-app'
    image: 'gixorian/flask-app:latest'
    restart: unless-stopped
    volumes:
      - ./app:/app
      - ./data:/data
    ports:
      - 5000:5000
    networks:
      web-net-50:
        ipv4_address: 172.50.0.10
